### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by GaryDeco**
- ignores broken symlink requiring user to manually delete prior to symlinking local ksp2 folder

### CODE REVIEW

**Comment by djungelorm** [comment]
Could you also delete the lib/ksp2 symlink from the repository?

**Comment by GaryDeco** [comment]
> Could you also delete the lib/ksp2 symlink from the repository?

I did this with the idea that you would place your symlink within a ksp2 folder and the contents would be ignored so symlinks were not uploaded to repo. If there needs to be a bazel BUILD script within the folder or something I can just ignore KSP_x64_Data?

**Comment by djungelorm** [comment]
> > Could you also delete the lib/ksp2 symlink from the repository?
> 
> I did this with the idea that you would place your symlink within a ksp2 folder and the contents would be ignored so symlinks were not uploaded to repo. If there needs to be a bazel BUILD script within the folder or something I can just ignore KSP_x64_Data? But this ignores the whole thing. so can make it lib/ksp2/

You can't have an empty directory in a git repository. The broken symlink still exists in the repository, and we should at least remove that.

**Comment by djungelorm** [comment]
Yeah I like that idea. Maybe call the file README.txt though?

**Comment by GaryDeco** [comment]
Sure. Arbitrary name. That works too!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
